config/routes.rb
MyGadgets::Application.routes.draw do
  resources :gadgets

  devise_for :users
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
    get "/sign_up" => "devise/registrations#new"
  end

  root 'dashboard#index'
end

app/models/gadget.rb
class Gadget
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Search

  field :name
  field :description

  belongs_to :user
  embeds_many :photos, cascade_callbacks: true

  accepts_nested_attributes_for :photos, allow_destroy: true

  validates_presence_of :name, :user

  scope :by_user_id, -> (user_id) { where(user_id: user_id) }

  search_in :name
end

app/models/photo.rb
class Photo
  include Mongoid::Document
  include Mongoid::Timestamps

  embedded_in :gadget

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type:  String, default: ""
  field :encrypted_password, type:  String, default: ""

  ## Recoverable
  field :reset_password_token,   type:  String
  field :reset_password_sent_at, type:  Time

  ## Rememberable
  field :remember_created_at, type:  Time

  ## Trackable
  field :sign_in_count,      type:  Integer, default: 0
  field :current_sign_in_at, type:  Time
  field :last_sign_in_at,    type:  Time
  field :current_sign_in_ip, type:  String
  field :last_sign_in_ip,    type:  String

  has_many :gadgets, dependent: :delete
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/gadgets_controller.rb
class GadgetsController < ApplicationController
  before_action :authenticate_user!

  def index
    @gadgets = GadgetSearch.new(current_user.id, params[:q]).search
  end

  def show
    @gadget = find_gadget
  end

  def new
    @gadget = Gadget.new
  end

  def edit
    @gadget = find_gadget
  end

  def create
    @gadget = Gadget.new(gadget_params)
    @gadget.user = current_user

    respond_to do |format|
      if @gadget.save
        format.html { redirect_to @gadget, notice: 'Gadget was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    @gadget = find_gadget

    respond_to do |format|
      if @gadget.update(gadget_params)
        format.html { redirect_to @gadget, notice: 'Gadget was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @gadget = find_gadget
    @gadget.destroy

    respond_to do |format|
      format.html { redirect_to gadgets_url }
    end
  end

  private
    def find_gadget
      Gadget.find(params[:id])
    end

    def gadget_params
      params.require(:gadget).permit(:name, :description, photos_attributes: [:id, :image, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_form_messages.html.erb
<% if object && object.respond_to?(:errors) && object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.model_name.human %> from being saved:</h2>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/dashboard/index.html.erb
<h1>Dashboard</h1>

<% if user_signed_in? %>
  <%= link_to "my gadgets", gadgets_path %> |
  <%= link_to "create gadget", new_gadget_path %>
<% else %>
  you should log in to manage gadgets
<% end %>

app/views/gadgets/_form.html.erb
<%= nested_form_for(gadget, html: {multipart: true }) do |f| %>
  <%= render "form_messages", object: gadget %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <%= f.fields_for :photos do |p| %>
    <div class="field">
      <%= image_tag p.object.image.thumb.url, width: 200, heigth: 150 %><br>
      <%= p.file_field :image, class: "image" %>
      <%= p.link_to_remove "remove" %>
    </div>
  <% end %>
  <p><%= f.link_to_add "add image", :photos %></p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gadgets/edit.html.erb
<h1>Editing gadget</h1>

<%= render 'form', gadget: @gadget %>

<br>
<%= link_to 'see details', @gadget %> |
<%= link_to 'my gadgets', gadgets_path %>

app/views/gadgets/index.html.erb
<h1>My gadgets</h1>

<%= form_tag({}, {method: :get}) do %>
  <%= text_field_tag :q %>
  <%= submit_tag "Search" %>
<% end %>

<table>
  <tbody>
    <% @gadgets.each do |gadget| %>
      <tr>
        <td><%= link_to gadget.name, gadget %></td>
        <td><%= link_to 'edit', edit_gadget_path(gadget) %></td>
        <td><%= link_to 'remove', gadget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Gadget', new_gadget_path %>

app/views/gadgets/new.html.erb
<h1>New gadget</h1>

<%= render 'form', gadget: @gadget %>

<br>
<%= link_to 'my gadgets', gadgets_path %>

app/views/gadgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= @gadget.name %>
</p>

<p>
  <%= @gadget.description %>
</p>

<ul>
  <% @gadget.photos.each do |photo| %>
    <%= image_tag photo.image.thumb.url %>
  <% end %>
</ul>

<%= link_to 'edit', edit_gadget_path(@gadget) %> |
<%= link_to 'my gadgets', gadgets_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyGadgets</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div>
    <% if user_signed_in? %>
      <%= current_user.email %> | <%= link_to "logout", logout_path, method: :delete %>
    <% else %>
      <%= link_to "login", login_path %> | <%= link_to "sign_up", sign_up_path %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>